# My Python app (running in a pod) has a safe, limited identity to access the Kubernetes API.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-monitoring-app
  namespace: python-monitoring-app
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: python-monitoring-app
  name: python-monitoring-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-monitoring-app-binding
  namespace: python-monitoring-app
subjects:
- kind: ServiceAccount
  name: python-monitoring-app
  namespace: python-monitoring-app
roleRef:
  kind: Role
  name: python-monitoring-app-role
  apiGroup: rbac.authorization.k8s.io
