---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-monitoring-app-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/python-app/logs  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-monitoring-app-pvc
  namespace: python-monitoring-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi